version: '3'
services:
    php-apache:
        build: ./docker
        ports:
            - 8080:80
        volumes:
            - ./src:/var/www/html
    php-apache-front:
        build: ./docker
        ports:
            - 80:80
        volumes:
            - ./view:/var/www/html